version: "3"

services:

  api_gateway:
    build: .
    image: ${DOCKER_REPO}:${API_GATEWAY_IMAGE_DEV_TAG:-latest-dev}
    ports:
      - "5001:5001"
    environment:
      ENV: DEV 
    # volumes:
    #   - ./api_gateway:/project/api_gateway
    depends_on:
      - redis
  
  redis:
    image: redis:3.2.8-alpine
